name: Azure Web App Deployment
on:
  push:
    branches:
      - dev  # or whatever your development branch is named

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Add any build steps here if needed
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: deploy/azure-web-app
        title: 'Deploy to Azure Web App'
        body: |
          Automated PR for Azure Web App deployment
          
          This PR was automatically created by the Azure Web App deployment workflow.
          Please review the changes before merging.
        
        base: main  # or master, depending on your default branch
        draft: false
        
    - name: Deploy to Azure Web App
      if: github.event.pull_request.merged == true
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .  # or your build output directory