name: Azure Web App Deployment
permissions:
  pull-requests: write
  contents: write
  
on:
  push:
    branches:
      - development
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create-pr:
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # This ensures all history is fetched
    
    - name: Debug Info
      run: |
        echo "Current branch: $(git branch --show-current)"
        echo "Git status:"
        git status
    
    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: deploy/azure-web-app
        title: 'Deploy to Azure Web App'
        body: |
          Automated PR for Azure Web App deployment
          
          This PR was automatically created by the Azure Web App deployment workflow.
          Please review the changes before merging.
        base: main
        draft: false

    - name: PR Creation Result
      run: |
        echo "PR Creation Output: ${{ steps.create-pr.outputs.pull-request-number }}"
        echo "PR URL: ${{ steps.create-pr.outputs.pull-request-url }}"

  deploy:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .